# Generated by Django 4.1.7 on 2023-03-22 18:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('email_address', models.EmailField(max_length=254, verbose_name='')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=40, region=None, verbose_name='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2, verbose_name='')),
                ('id_card', models.CharField(choices=[('G', 'Ghana Card'), ('N', 'National Health_Insurance Card'), ('V', "Voter's ID Card"), ('S', "Student's ID"), ('D', "Driver's License")], default='G', max_length=2, verbose_name='')),
                ('id_number', models.CharField(max_length=10, verbose_name='')),
            ],
        ),
    ]
