# Generated by Django 4.1.7 on 2023-03-20 20:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True, region=None)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2)),
                ('id_card', models.CharField(choices=[('G', 'Ghana_Card'), ('N', 'National_Health_Insurance_Card'), ('V', "Voter's_ID_Card"), ('S', "Student's_ID"), ('D', "Driver's_License")], default='G', max_length=2)),
                ('id_number', models.CharField(max_length=200)),
            ],
        ),
    ]
