# Generated by Django 4.1.7 on 2023-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
