# Generated by Django 4.1.7 on 2023-03-20 21:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True, region=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_card',
            field=models.CharField(choices=[('G', 'Ghana Card'), ('N', 'National Health_Insurance Card'), ('V', "Voter's ID Card"), ('S', "Student's ID"), ('D', "Driver's License")], default='G', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_number',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
